-- MySQL Script generated by MySQL Workbench
-- Fri May 26 19:01:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` INT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_producto` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_marca` INT NOT NULL,
  `id_tipo_producto` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `id_tipo_producto`),
  INDEX `fk_producto_marca_idx` (`id_marca` ASC) VISIBLE,
  INDEX `fk_producto_tipo_producto1_idx` (`id_tipo_producto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `mydb`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_tipo_producto1`
    FOREIGN KEY (`id_tipo_producto`)
    REFERENCES `mydb`.`tipo_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`condiciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`condiciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reg_op` VARCHAR(45) NULL,
  `fecha_emision` DATETIME NULL,
  `compracol` VARCHAR(45) NULL,
  `fecha_vencimiento` DATETIME NULL,
  `no_comprobante` VARCHAR(45) NULL,
  `id_proveedor` VARCHAR(45) NULL,
  `razon_social_proveedor` VARCHAR(120) NULL,
  `descuentos_iva` VARCHAR(45) NULL,
  `importe_total` VARCHAR(45) NULL,
  `condiciones_id` INT NULL,
  `estado_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `estado_id`),
  INDEX `fk_compra_condiciones1_idx` (`condiciones_id` ASC) VISIBLE,
  INDEX `fk_compra_estado1_idx` (`estado_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_compra_condiciones1`
    FOREIGN KEY (`condiciones_id`)
    REFERENCES `mydb`.`condiciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_compra` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidad_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidad_medida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `abrevitura` VARCHAR(45) NULL,
  `estado` INT NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_compra_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_compra_productos` (
  `id_detalle_compra` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_compra` INT NOT NULL,
  `id_unidad_medida` INT NOT NULL,
  `cantidad` INT NULL,
  `precio_compra` FLOAT NULL,
  `precio_venta` FLOAT NULL,
  `referencia` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_detalle_compra`, `id_unidad_medida`),
  INDEX `fk_producto_has_compra_compra1_idx` (`id_compra` ASC) VISIBLE,
  INDEX `fk_producto_has_compra_producto1_idx` (`id_producto` ASC) VISIBLE,
  INDEX `fk_detalle_compra_productos_unidad_medida1_idx` (`id_unidad_medida` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_compra_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_compra_compra1`
    FOREIGN KEY (`id_compra`)
    REFERENCES `mydb`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_compra_productos_unidad_medida1`
    FOREIGN KEY (`id_unidad_medida`)
    REFERENCES `mydb`.`unidad_medida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `imagen` VARCHAR(45) NULL,
  `nomenclatura` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paquete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_paquete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `precio_venta` INT NULL,
  `porcentaje` INT NULL,
  `id_tipo_vehiculo` INT NOT NULL,
  `id_paquete` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `id_tipo_vehiculo`, `id_paquete`),
  INDEX `fk_paquete_tipo_vehiculo1_idx` (`id_tipo_vehiculo` ASC) VISIBLE,
  INDEX `fk_paquete_paquete1_idx` (`id_paquete` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_paquete_tipo_vehiculo1`
    FOREIGN KEY (`id_tipo_vehiculo`)
    REFERENCES `mydb`.`tipo_vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquete_paquete1`
    FOREIGN KEY (`id_paquete`)
    REFERENCES `mydb`.`paquete` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `nombre_cliente` VARCHAR(80) NULL,
  `placa` VARCHAR(45) NULL,
  `numero_telefono` VARCHAR(45) NULL,
  `id_detalle_paquete` INT NULL,
  `id_tipo_vehiculo_detalle_paquete` INT NULL,
  `id_paquete_detalle_paquete` INT NULL,
  `id_usuario` INT NULL,
  `id_estado_venta` INT NOT NULL COMMENT '1 = Pendiente por pagar , 2 = Servicio pagado , 3 = Venta Interna',
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `id_detalle_paquete`, `id_tipo_vehiculo_detalle_paquete`, `id_paquete_detalle_paquete`, `id_estado_venta`),
  INDEX `fk_venta_detalle_paquete1_idx` (`id_detalle_paquete` ASC, `id_tipo_vehiculo_detalle_paquete` ASC, `id_paquete_detalle_paquete` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_venta_estado_venta1_idx` (`id_estado_venta` ASC) VISIBLE,
  CONSTRAINT `fk_venta_detalle_paquete1`
    FOREIGN KEY (`id_detalle_paquete` , `id_tipo_vehiculo_detalle_paquete` , `id_paquete_detalle_paquete`)
    REFERENCES `mydb`.`detalle_paquete` (`id` , `id_tipo_vehiculo` , `id_paquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_estado_venta1`
    FOREIGN KEY (`id_estado_venta`)
    REFERENCES `mydb`.`estado_venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicio_paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicio_paquete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_servicio` INT NOT NULL,
  `id_paquete` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `id_paquete`),
  INDEX `fk_servicio_tipo_vehiculo_servicio1_idx` (`id_servicio` ASC) VISIBLE,
  INDEX `fk_servicio_tipo_vehiculo_paquete1_idx` (`id_paquete` ASC) VISIBLE,
  CONSTRAINT `fk_servicio_tipo_vehiculo_servicio1`
    FOREIGN KEY (`id_servicio`)
    REFERENCES `mydb`.`servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_tipo_vehiculo_paquete1`
    FOREIGN KEY (`id_paquete`)
    REFERENCES `mydb`.`detalle_paquete` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`egresos_concepto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`egresos_concepto` (
  `id` INT NOT NULL,
  `concepto` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`egresos_mensuales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`egresos_mensuales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `id_concepto` INT NOT NULL,
  `total_egreso` INT NULL,
  PRIMARY KEY (`id`, `id_concepto`),
  INDEX `fk_egresos_mensuales_egresos_concepto1_idx` (`id_concepto` ASC) VISIBLE,
  CONSTRAINT `fk_egresos_mensuales_egresos_concepto1`
    FOREIGN KEY (`id_concepto`)
    REFERENCES `mydb`.`egresos_concepto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_venta_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_venta_productos` (
  `id_venta` INT NOT NULL,
  `cantidad` INT NULL,
  `id_producto` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_venta`, `id_producto`),
  INDEX `fk_venta_has_detalle_compra_productos_venta1_idx` (`id_venta` ASC) VISIBLE,
  INDEX `fk_detalle_venta_productos_producto1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_venta_has_detalle_compra_productos_venta1`
    FOREIGN KEY (`id_venta`)
    REFERENCES `mydb`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_productos_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
